package clases;

public class Femenil extends Jugador {
@Override
public void Datos() {
	System.out.println("/nNombres de los integrantes del primer equipo:\n"
			                +"Primer jugador: \n"
							+"Nombre: Elisa Aguilar \n"
							+"Direcci�n: Oaxaca \n"
							+"Edad: 32 \n"
							+"Tel�fono:951 302 12 34 \n"
							+"Segundo jugador: \n"
							+"Nombre: Nieves Anula \n"
							+"Direcci�n: Oaxaca \n"
							+"Edad: 32\n"
							+"Tel�fono:9513929282\n"
							+"Tercero jugador:\n"
							+"Nombre: Blanca Ares\n"
						    +"Direcci�n: Oaxaca\n"
							+"Edad: 21 \n"
							+"Tel�fono:9513201221 \n"
							+"Cuarto jugador: \n"
							+"Nombre: Rosa Castillo \n"
							+"Direcci�n: Oaxaca \n"
							+"Edad: 21 \n"
							+"Tel�fono:9512322332 \n"
							+"Quinto jugador:\n"
							+"Nombre: Betty Cebri�n \n"
							+"Direcci�n: Oaxaca \n"
							+"Edad: 20 \n"
							+"Tel�fono:951123221\n\n"
							+"Nombre del segundo equipo femenil: NBA\n"
							+"Faltas del segundo equipo femenil:  0 \n"
							+"Nombres de los integrantes del segundo equipo:\n"							
							+"Primer jugador:\n"
							+"Nombre: Margo Dydek\n"
							+"Direcci�n: Oaxaca \n"
							+"Edad:19 \n"
							+"Tel�fono:9512321232\n"
							+"Segundo jugador:\n"
							+"Segundo jugador:\n"
							+"Nombre: Marta Fern�ndez \n"
							+"Direcci�n: Oaxaca\n"
							+"Edad:23\n"
							+"Tel�fono:95122324323\n"
							+"Tercero jugador:\n"
							+"Nombre: Marina Ferragut\n"
							+"Direcci�n: Oaxaca\n"
							+"Edad:43\n"
							+"Tel�fono:9512331253\n"
							+"Cuarto jugador:\n"
							+"Primer jugador:\n"
							+"Nombre: Becky Hammon \n"
							+"Direcci�n: Oaxaca \n"
							+"Edad:32\n"
							+"Tel�fono:9511234323\n"
							+"Quinto jugador:\n"
							+"Nombre: Kedra Holland Korn\n"
							+"Direcci�n: Oaxaca\n"
							+"Edad:23\n"
				            +"Tel�fono:9511232232\n");	
			}
}

